sudo: true
language: php
php:
  - 5.4
  - 5.5
branches:
  only:
    - /^7.x/
env:
  - FEDORA_VERSION="3.8.1"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solr_search.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_csv_to_mods
  - drush en --yes --user=1 islandora_csv_to_mods
script:
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_csv_to_mods
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_csv_to_mods
  - phpcpd --names *.module,*.inc sites/all/modules/islandora_csv_to_mods
  - drush test-run --uri=http://localhost:8081 "Islandora CSV to MODS Utility"
